// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AddPlayerResponseObject is an autogenerated mock type for the AddPlayerResponseObject type
type AddPlayerResponseObject struct {
	mock.Mock
}

// VisitAddPlayerResponse provides a mock function with given fields: w
func (_m *AddPlayerResponseObject) VisitAddPlayerResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitAddPlayerResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddPlayerResponseObject creates a new instance of AddPlayerResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddPlayerResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddPlayerResponseObject {
	mock := &AddPlayerResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
