// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	oapiprivate "common/oapiprivate"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// AddPlayerWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) AddPlayerWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...oapiprivate.RequestEditorFn) (*oapiprivate.AddPlayerResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayerWithBodyWithResponse")
	}

	var r0 *oapiprivate.AddPlayerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapiprivate.RequestEditorFn) (*oapiprivate.AddPlayerResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapiprivate.RequestEditorFn) *oapiprivate.AddPlayerResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapiprivate.AddPlayerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...oapiprivate.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddPlayerWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientWithResponsesInterface) AddPlayerWithResponse(ctx context.Context, body oapiprivate.AddPlayerJSONRequestBody, reqEditors ...oapiprivate.RequestEditorFn) (*oapiprivate.AddPlayerResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddPlayerWithResponse")
	}

	var r0 *oapiprivate.AddPlayerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.AddPlayerJSONRequestBody, ...oapiprivate.RequestEditorFn) (*oapiprivate.AddPlayerResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.AddPlayerJSONRequestBody, ...oapiprivate.RequestEditorFn) *oapiprivate.AddPlayerResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapiprivate.AddPlayerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.AddPlayerJSONRequestBody, ...oapiprivate.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) DashboardWithResponse(ctx context.Context, reqEditors ...oapiprivate.RequestEditorFn) (*oapiprivate.DashboardResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DashboardWithResponse")
	}

	var r0 *oapiprivate.DashboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) (*oapiprivate.DashboardResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) *oapiprivate.DashboardResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapiprivate.DashboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...oapiprivate.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoggedInUserWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) GetLoggedInUserWithResponse(ctx context.Context, reqEditors ...oapiprivate.RequestEditorFn) (*oapiprivate.GetLoggedInUserResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetLoggedInUserWithResponse")
	}

	var r0 *oapiprivate.GetLoggedInUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) (*oapiprivate.GetLoggedInUserResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) *oapiprivate.GetLoggedInUserResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapiprivate.GetLoggedInUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...oapiprivate.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) LogoutWithResponse(ctx context.Context, reqEditors ...oapiprivate.RequestEditorFn) (*oapiprivate.LogoutResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LogoutWithResponse")
	}

	var r0 *oapiprivate.LogoutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) (*oapiprivate.LogoutResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...oapiprivate.RequestEditorFn) *oapiprivate.LogoutResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapiprivate.LogoutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...oapiprivate.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
