// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	oapipublic "common/oapipublic"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

// LoginWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) LoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...oapipublic.RequestEditorFn) (*oapipublic.LoginResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithBodyWithResponse")
	}

	var r0 *oapipublic.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) (*oapipublic.LoginResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) *oapipublic.LoginResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapipublic.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientWithResponsesInterface) LoginWithResponse(ctx context.Context, body oapipublic.LoginJSONRequestBody, reqEditors ...oapipublic.RequestEditorFn) (*oapipublic.LoginResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithResponse")
	}

	var r0 *oapipublic.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapipublic.LoginJSONRequestBody, ...oapipublic.RequestEditorFn) (*oapipublic.LoginResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapipublic.LoginJSONRequestBody, ...oapipublic.RequestEditorFn) *oapipublic.LoginResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapipublic.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapipublic.LoginJSONRequestBody, ...oapipublic.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) RefreshTokenWithResponse(ctx context.Context, reqEditors ...oapipublic.RequestEditorFn) (*oapipublic.RefreshTokenResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenWithResponse")
	}

	var r0 *oapipublic.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...oapipublic.RequestEditorFn) (*oapipublic.RefreshTokenResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...oapipublic.RequestEditorFn) *oapipublic.RefreshTokenResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapipublic.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...oapipublic.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignupWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *ClientWithResponsesInterface) SignupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...oapipublic.RequestEditorFn) (*oapipublic.SignupResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SignupWithBodyWithResponse")
	}

	var r0 *oapipublic.SignupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) (*oapipublic.SignupResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) *oapipublic.SignupResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapipublic.SignupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...oapipublic.RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignupWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *ClientWithResponsesInterface) SignupWithResponse(ctx context.Context, body oapipublic.SignupJSONRequestBody, reqEditors ...oapipublic.RequestEditorFn) (*oapipublic.SignupResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SignupWithResponse")
	}

	var r0 *oapipublic.SignupResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapipublic.SignupJSONRequestBody, ...oapipublic.RequestEditorFn) (*oapipublic.SignupResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapipublic.SignupJSONRequestBody, ...oapipublic.RequestEditorFn) *oapipublic.SignupResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oapipublic.SignupResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapipublic.SignupJSONRequestBody, ...oapipublic.RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
