// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// EndGameResponseObject is an autogenerated mock type for the EndGameResponseObject type
type EndGameResponseObject struct {
	mock.Mock
}

// VisitEndGameResponse provides a mock function with given fields: w
func (_m *EndGameResponseObject) VisitEndGameResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitEndGameResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEndGameResponseObject creates a new instance of EndGameResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEndGameResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *EndGameResponseObject {
	mock := &EndGameResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
