// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "common/models"

	oapiprivate "common/oapiprivate"
)

// GameServiceInterface is an autogenerated mock type for the GameServiceInterface type
type GameServiceInterface struct {
	mock.Mock
}

// AddGameSteps provides a mock function with given fields: ctx, input
func (_m *GameServiceInterface) AddGameSteps(ctx context.Context, input oapiprivate.AddGameStepsRequestObject) (oapiprivate.AddGameStepsResponseObject, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddGameSteps")
	}

	var r0 oapiprivate.AddGameStepsResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.AddGameStepsRequestObject) (oapiprivate.AddGameStepsResponseObject, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.AddGameStepsRequestObject) oapiprivate.AddGameStepsResponseObject); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oapiprivate.AddGameStepsResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.AddGameStepsRequestObject) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGameSteps provides a mock function with given fields: ctx, input
func (_m *GameServiceInterface) DeleteGameSteps(ctx context.Context, input oapiprivate.DeleteGameStepsRequestObject) (oapiprivate.DeleteGameStepsResponseObject, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGameSteps")
	}

	var r0 oapiprivate.DeleteGameStepsResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.DeleteGameStepsRequestObject) (oapiprivate.DeleteGameStepsResponseObject, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.DeleteGameStepsRequestObject) oapiprivate.DeleteGameStepsResponseObject); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oapiprivate.DeleteGameStepsResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.DeleteGameStepsRequestObject) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndGame provides a mock function with given fields: ctx, input
func (_m *GameServiceInterface) EndGame(ctx context.Context, input oapiprivate.EndGameRequestObject) (oapiprivate.EndGameResponseObject, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for EndGame")
	}

	var r0 oapiprivate.EndGameResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.EndGameRequestObject) (oapiprivate.EndGameResponseObject, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.EndGameRequestObject) oapiprivate.EndGameResponseObject); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oapiprivate.EndGameResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.EndGameRequestObject) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGame provides a mock function with given fields: ctx, input
func (_m *GameServiceInterface) GetGame(ctx context.Context, input oapiprivate.GetGameRequestObject) (oapiprivate.GetGameResponseObject, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetGame")
	}

	var r0 oapiprivate.GetGameResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.GetGameRequestObject) (oapiprivate.GetGameResponseObject, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.GetGameRequestObject) oapiprivate.GetGameResponseObject); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oapiprivate.GetGameResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.GetGameRequestObject) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartGame provides a mock function with given fields: ctx, input, user
func (_m *GameServiceInterface) StartGame(ctx context.Context, input oapiprivate.StartGameRequestObject, user models.User) (oapiprivate.StartGameResponseObject, error) {
	ret := _m.Called(ctx, input, user)

	if len(ret) == 0 {
		panic("no return value specified for StartGame")
	}

	var r0 oapiprivate.StartGameResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.StartGameRequestObject, models.User) (oapiprivate.StartGameResponseObject, error)); ok {
		return rf(ctx, input, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, oapiprivate.StartGameRequestObject, models.User) oapiprivate.StartGameResponseObject); ok {
		r0 = rf(ctx, input, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oapiprivate.StartGameResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, oapiprivate.StartGameRequestObject, models.User) error); ok {
		r1 = rf(ctx, input, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGameServiceInterface creates a new instance of GameServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameServiceInterface {
	mock := &GameServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
