// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// GetPlayerWithIdResponseObject is an autogenerated mock type for the GetPlayerWithIdResponseObject type
type GetPlayerWithIdResponseObject struct {
	mock.Mock
}

// VisitGetPlayerWithIdResponse provides a mock function with given fields: w
func (_m *GetPlayerWithIdResponseObject) VisitGetPlayerWithIdResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitGetPlayerWithIdResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGetPlayerWithIdResponseObject creates a new instance of GetPlayerWithIdResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetPlayerWithIdResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetPlayerWithIdResponseObject {
	mock := &GetPlayerWithIdResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
