// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ListPlayersResponseObject is an autogenerated mock type for the ListPlayersResponseObject type
type ListPlayersResponseObject struct {
	mock.Mock
}

// VisitListPlayersResponse provides a mock function with given fields: w
func (_m *ListPlayersResponseObject) VisitListPlayersResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitListPlayersResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewListPlayersResponseObject creates a new instance of ListPlayersResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListPlayersResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListPlayersResponseObject {
	mock := &ListPlayersResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
