// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	models "common/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PlayerRepository is an autogenerated mock type for the PlayerRepository type
type PlayerRepository struct {
	mock.Mock
}

// CreatePlayer provides a mock function with given fields: ctx, toCreate, passwordHash
func (_m *PlayerRepository) CreatePlayer(ctx context.Context, toCreate models.Player, passwordHash string) (models.Player, error) {
	ret := _m.Called(ctx, toCreate, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlayer")
	}

	var r0 models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Player, string) (models.Player, error)); ok {
		return rf(ctx, toCreate, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Player, string) models.Player); ok {
		r0 = rf(ctx, toCreate, passwordHash)
	} else {
		r0 = ret.Get(0).(models.Player)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Player, string) error); ok {
		r1 = rf(ctx, toCreate, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlayerRepository creates a new instance of PlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerRepository {
	mock := &PlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
