// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	oapiprivate "common/oapiprivate"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

// AddGameSteps provides a mock function with given fields: w, r, gameId
func (_m *ServerInterface) AddGameSteps(w http.ResponseWriter, r *http.Request, gameId string) {
	_m.Called(w, r, gameId)
}

// AddPlayer provides a mock function with given fields: w, r
func (_m *ServerInterface) AddPlayer(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// CreateOrUpdateGameHistory provides a mock function with given fields: w, r, gameId
func (_m *ServerInterface) CreateOrUpdateGameHistory(w http.ResponseWriter, r *http.Request, gameId string) {
	_m.Called(w, r, gameId)
}

// Dashboard provides a mock function with given fields: w, r
func (_m *ServerInterface) Dashboard(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeleteGameSteps provides a mock function with given fields: w, r, gameId
func (_m *ServerInterface) DeleteGameSteps(w http.ResponseWriter, r *http.Request, gameId string) {
	_m.Called(w, r, gameId)
}

// EndGame provides a mock function with given fields: w, r, gameId
func (_m *ServerInterface) EndGame(w http.ResponseWriter, r *http.Request, gameId string) {
	_m.Called(w, r, gameId)
}

// GetGameHistory provides a mock function with given fields: w, r, gameId
func (_m *ServerInterface) GetGameHistory(w http.ResponseWriter, r *http.Request, gameId string) {
	_m.Called(w, r, gameId)
}

// GetLoggedInUser provides a mock function with given fields: w, r
func (_m *ServerInterface) GetLoggedInUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetPlayerWithId provides a mock function with given fields: w, r, id
func (_m *ServerInterface) GetPlayerWithId(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// ListPlayers provides a mock function with given fields: w, r, params
func (_m *ServerInterface) ListPlayers(w http.ResponseWriter, r *http.Request, params oapiprivate.ListPlayersParams) {
	_m.Called(w, r, params)
}

// Logout provides a mock function with given fields: w, r
func (_m *ServerInterface) Logout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// StartGame provides a mock function with given fields: w, r
func (_m *ServerInterface) StartGame(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdatePlayerWithId provides a mock function with given fields: w, r, id
func (_m *ServerInterface) UpdatePlayerWithId(w http.ResponseWriter, r *http.Request, id string) {
	_m.Called(w, r, id)
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
