// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// SignupResponseObject is an autogenerated mock type for the SignupResponseObject type
type SignupResponseObject struct {
	mock.Mock
}

// VisitSignupResponse provides a mock function with given fields: w
func (_m *SignupResponseObject) VisitSignupResponse(w http.ResponseWriter) error {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for VisitSignupResponse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) error); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSignupResponseObject creates a new instance of SignupResponseObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignupResponseObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignupResponseObject {
	mock := &SignupResponseObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
