steps:
  # Build Go app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "internal/Dockerfile.prod",
        "-t",
        "gcr.io/badminton-stats-441017/badminton-api",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/badminton-stats-441017/badminton-api"]

  # Deploy Go app to Cloud Run with secrets
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "badminton-api-service"
      - "--image"
      - "gcr.io/badminton-stats-441017/badminton-api"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--no-allow-unauthenticated"
      - "--set-secrets"
      - "DB_URI=projects/709018077748/secrets/db-uri:latest"
      - "--set-secrets"
      - "CORS_ALLOWED_ORIGINS=projects/709018077748/secrets/cors-origin:latest"
      - "--set-secrets"
      - "SESSION_LIFESPAN_MINUTES=projects/709018077748/secrets/session-lifespan-minutes:latest"
      - "--set-secrets"
      - "REFRESH_LIFESPAN_MINUTES=projects/709018077748/secrets/refresh-lifespan-minutes:latest"
      - "--set-secrets"
      - "IS_HTTPS=projects/709018077748/secrets/is-https:latest"
      - "--set-secrets"
      - "APP_PORT=projects/709018077748/secrets/app-port:latest"

  # Build Vue app, using the secret directly as an environment variable
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "web/Dockerfile.prod",
        "-t",
        "gcr.io/badminton-stats-441017/badminton-frontend",
        ".",
        "--build-arg",
        "VITE_BACKEND_URL=$VITE_BACKEND_URL",
      ]
    secretEnv: ["VITE_BACKEND_URL"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/badminton-stats-441017/badminton-frontend"]

  # Deploy Vue app to Cloud Run with secrets
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "badminton-frontend-service"
      - "--image"
      - "gcr.io/badminton-stats-441017/badminton-frontend"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-secrets"
      - "VITE_BACKEND_URL=projects/709018077748/secrets/vite-backend-url:latest"

images:
  [
    "gcr.io/badminton-stats-441017/badminton-api",
    "gcr.io/badminton-stats-441017/badminton-frontend",
  ]

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/709018077748/secrets/vite-backend-url/versions/latest"
      env: "VITE_BACKEND_URL"
