steps:
  # Build Go app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./internal/Dockerfile.prod",
        "-t",
        "gcr.io/$PROJECT_ID/badminton-api",
        ".",
      ]
    secretEnv:
      [
        "DB_URI",
        "CORS_ALLOWED_ORIGINS",
        "SESSION_LIFESPAN_MINUTES",
        "REFRESH_LIFESPAN_MINUTES",
        "IS_HTTPS",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/badminton-api"]

  # Deploy Go app to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "badminton-api-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/badminton-api"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--no-allow-unauthenticated"

  # Build Vue app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./web/Dockerfile.prod",
        "-t",
        "gcr.io/$PROJECT_ID/badminton-frontend",
        ".",
      ]
    secretEnv: ["VITE_BACKEND_URL=${_API_URL}"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/badminton-frontend"]

  # Deploy Vue app to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "badminton-frontend-service"
      - "--image"
      - "gcr.io/$PROJECT_ID/vue-app"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/badminton-api"
  - "gcr.io/$PROJECT_ID/badminton-frontend"

availableSecrets:
  - secretManager: "projects/$PROJECT_ID/secrets/db-uri/versions/latest"
    env: "DB_URI"
  - secretManager: "projects/$PROJECT_ID/secrets/cors-origin/versions/latest"
    env: "CORS_ALLOWED_ORIGINS"
  - secretManager: "projects/$PROJECT_ID/secrets/session-lifespan-minutes/versions/latest"
    env: "SESSION_LIFESPAN_MINUTES"
  - secretManager: "projects/$PROJECT_ID/secrets/refresh-lifespan-minutes/versions/latest"
    env: "REFRESH_LIFESPAN_MINUTES"
  - secretManager: "projects/$PROJECT_ID/secrets/is-https/versions/latest"
    env: "IS_HTTPS"

substitutions:
  _API_URL: "https://your-production-api-url.com" # Default production API URL
