services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
    ports:
      - "8080:5173"
    depends_on:
      - http
    env_file:
      - .env
      
  gcp-proxy:
    build:
      context: docker/app
    volumes:
      - ./gcp-proxy:/gcp-proxy
    working_dir: /gcp-proxy
    ports:
      - "$PROXY_PORT:8080"
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - tzetypes-badminton-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "$APP_PORT:$APP_PORT"
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - gcp-proxy
  
  tzetypes-badminton-db:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    container_name: tzetypes-badminton-db
    volumes:
    - tzetypes-badminton-pg-data:/var/lib/postgresql/data

volumes:
  tzetypes-badminton-pg-data:

