services:
  http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "$APP_PORT:$APP_PORT"
    environment:
      SERVER_TO_RUN: http
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - template-db
  
  template-db:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    container_name: template-db
    volumes:
    - template-pg-data:/var/lib/postgresql/data
    - ./db:/docker-entrypoint-initdb.d/

volumes:
  template-pg-data:

