// Package oapipublic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapipublic

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// End games which are abandoned after a time
	// (GET /end-abandoned-games)
	EndAbandonedGames(w http.ResponseWriter, r *http.Request)
	// Get game statistics
	// (GET /game/{game_id}/statistics)
	GetGameStatistics(w http.ResponseWriter, r *http.Request, gameId string)
	// Generate statistics for players that has latest game in timespan
	// (GET /generate-recent-statistics)
	GenerateRecentStatistics(w http.ResponseWriter, r *http.Request)
	// Get latest media which is posted
	// (GET /get-instagram-feed)
	GetInstagramFeed(w http.ResponseWriter, r *http.Request)
	// Update db with latest media
	// (GET /update-instagram-feed)
	UpdateInstagramFeed(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// End games which are abandoned after a time
// (GET /end-abandoned-games)
func (_ Unimplemented) EndAbandonedGames(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game statistics
// (GET /game/{game_id}/statistics)
func (_ Unimplemented) GetGameStatistics(w http.ResponseWriter, r *http.Request, gameId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate statistics for players that has latest game in timespan
// (GET /generate-recent-statistics)
func (_ Unimplemented) GenerateRecentStatistics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get latest media which is posted
// (GET /get-instagram-feed)
func (_ Unimplemented) GetInstagramFeed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update db with latest media
// (GET /update-instagram-feed)
func (_ Unimplemented) UpdateInstagramFeed(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// EndAbandonedGames operation middleware
func (siw *ServerInterfaceWrapper) EndAbandonedGames(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EndAbandonedGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameStatistics operation middleware
func (siw *ServerInterfaceWrapper) GetGameStatistics(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "game_id" -------------
	var gameId string

	err = runtime.BindStyledParameterWithOptions("simple", "game_id", chi.URLParam(r, "game_id"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "game_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameStatistics(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateRecentStatistics operation middleware
func (siw *ServerInterfaceWrapper) GenerateRecentStatistics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateRecentStatistics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstagramFeed operation middleware
func (siw *ServerInterfaceWrapper) GetInstagramFeed(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstagramFeed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateInstagramFeed operation middleware
func (siw *ServerInterfaceWrapper) UpdateInstagramFeed(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateInstagramFeed(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/end-abandoned-games", wrapper.EndAbandonedGames)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/game/{game_id}/statistics", wrapper.GetGameStatistics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/generate-recent-statistics", wrapper.GenerateRecentStatistics)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/get-instagram-feed", wrapper.GetInstagramFeed)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/update-instagram-feed", wrapper.UpdateInstagramFeed)
	})

	return r
}

type ErrorResponseSchemaJSONResponse Error

type EndAbandonedGamesRequestObject struct {
}

type EndAbandonedGamesResponseObject interface {
	VisitEndAbandonedGamesResponse(w http.ResponseWriter) error
}

type EndAbandonedGames200Response struct {
}

func (response EndAbandonedGames200Response) VisitEndAbandonedGamesResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type EndAbandonedGamesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response EndAbandonedGamesdefaultJSONResponse) VisitEndAbandonedGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetGameStatisticsRequestObject struct {
	GameId string `json:"game_id"`
}

type GetGameStatisticsResponseObject interface {
	VisitGetGameStatisticsResponse(w http.ResponseWriter) error
}

type GetGameStatistics200JSONResponse struct {
	Game       Game           `json:"game"`
	Statistics *GameStatistic `json:"statistics,omitempty"`
	Steps      []GameStep     `json:"steps"`
}

func (response GetGameStatistics200JSONResponse) VisitGetGameStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameStatisticsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetGameStatisticsdefaultJSONResponse) VisitGetGameStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GenerateRecentStatisticsRequestObject struct {
}

type GenerateRecentStatisticsResponseObject interface {
	VisitGenerateRecentStatisticsResponse(w http.ResponseWriter) error
}

type GenerateRecentStatistics200Response struct {
}

func (response GenerateRecentStatistics200Response) VisitGenerateRecentStatisticsResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GenerateRecentStatisticsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GenerateRecentStatisticsdefaultJSONResponse) VisitGenerateRecentStatisticsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetInstagramFeedRequestObject struct {
}

type GetInstagramFeedResponseObject interface {
	VisitGetInstagramFeedResponse(w http.ResponseWriter) error
}

type GetInstagramFeed200JSONResponse struct {
	Feed []InstagramMedia `json:"feed"`
}

func (response GetInstagramFeed200JSONResponse) VisitGetInstagramFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInstagramFeeddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetInstagramFeeddefaultJSONResponse) VisitGetInstagramFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateInstagramFeedRequestObject struct {
}

type UpdateInstagramFeedResponseObject interface {
	VisitUpdateInstagramFeedResponse(w http.ResponseWriter) error
}

type UpdateInstagramFeed200Response struct {
}

func (response UpdateInstagramFeed200Response) VisitUpdateInstagramFeedResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateInstagramFeeddefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateInstagramFeeddefaultJSONResponse) VisitUpdateInstagramFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// End games which are abandoned after a time
	// (GET /end-abandoned-games)
	EndAbandonedGames(ctx context.Context, request EndAbandonedGamesRequestObject) (EndAbandonedGamesResponseObject, error)
	// Get game statistics
	// (GET /game/{game_id}/statistics)
	GetGameStatistics(ctx context.Context, request GetGameStatisticsRequestObject) (GetGameStatisticsResponseObject, error)
	// Generate statistics for players that has latest game in timespan
	// (GET /generate-recent-statistics)
	GenerateRecentStatistics(ctx context.Context, request GenerateRecentStatisticsRequestObject) (GenerateRecentStatisticsResponseObject, error)
	// Get latest media which is posted
	// (GET /get-instagram-feed)
	GetInstagramFeed(ctx context.Context, request GetInstagramFeedRequestObject) (GetInstagramFeedResponseObject, error)
	// Update db with latest media
	// (GET /update-instagram-feed)
	UpdateInstagramFeed(ctx context.Context, request UpdateInstagramFeedRequestObject) (UpdateInstagramFeedResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// EndAbandonedGames operation middleware
func (sh *strictHandler) EndAbandonedGames(w http.ResponseWriter, r *http.Request) {
	var request EndAbandonedGamesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EndAbandonedGames(ctx, request.(EndAbandonedGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EndAbandonedGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EndAbandonedGamesResponseObject); ok {
		if err := validResponse.VisitEndAbandonedGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameStatistics operation middleware
func (sh *strictHandler) GetGameStatistics(w http.ResponseWriter, r *http.Request, gameId string) {
	var request GetGameStatisticsRequestObject

	request.GameId = gameId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameStatistics(ctx, request.(GetGameStatisticsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameStatistics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameStatisticsResponseObject); ok {
		if err := validResponse.VisitGetGameStatisticsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateRecentStatistics operation middleware
func (sh *strictHandler) GenerateRecentStatistics(w http.ResponseWriter, r *http.Request) {
	var request GenerateRecentStatisticsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateRecentStatistics(ctx, request.(GenerateRecentStatisticsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateRecentStatistics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GenerateRecentStatisticsResponseObject); ok {
		if err := validResponse.VisitGenerateRecentStatisticsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstagramFeed operation middleware
func (sh *strictHandler) GetInstagramFeed(w http.ResponseWriter, r *http.Request) {
	var request GetInstagramFeedRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstagramFeed(ctx, request.(GetInstagramFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstagramFeed")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstagramFeedResponseObject); ok {
		if err := validResponse.VisitGetInstagramFeedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateInstagramFeed operation middleware
func (sh *strictHandler) UpdateInstagramFeed(w http.ResponseWriter, r *http.Request) {
	var request UpdateInstagramFeedRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInstagramFeed(ctx, request.(UpdateInstagramFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInstagramFeed")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateInstagramFeedResponseObject); ok {
		if err := validResponse.VisitUpdateInstagramFeedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
