// Package oapipublic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package oapipublic

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Game defines model for Game.
type Game struct {
	ClubId              string `json:"club_id"`
	CreatedAt           string `json:"created_at"`
	GameType            string `json:"game_type"`
	Id                  string `json:"id"`
	IsEnded             bool   `json:"is_ended"`
	LeftEvenPlayerName  string `json:"left_even_player_name"`
	LeftOddPlayerName   string `json:"left_odd_player_name"`
	RightEvenPlayerName string `json:"right_even_player_name"`
	RightOddPlayerName  string `json:"right_odd_player_name"`
	ServingSide         string `json:"serving_side"`
	UpdatedAt           string `json:"updated_at"`
}

// GameStatistics defines model for GameStatistics.
type GameStatistics struct {
	TotalGameTime string `json:"total_game_time"`
}

// GameStep defines model for GameStep.
type GameStep struct {
	CreatedAt           string  `json:"created_at"`
	CurrentServer       string  `json:"current_server"`
	GameId              string  `json:"game_id"`
	Id                  string  `json:"id"`
	LeftEvenPlayerName  string  `json:"left_even_player_name"`
	LeftOddPlayerName   string  `json:"left_odd_player_name"`
	RightEvenPlayerName string  `json:"right_even_player_name"`
	RightOddPlayerName  string  `json:"right_odd_player_name"`
	ScoreAt             string  `json:"score_at"`
	StepNum             int     `json:"step_num"`
	SyncId              *string `json:"sync_id,omitempty"`
	TeamLeftScore       int     `json:"team_left_score"`
	TeamRightScore      int     `json:"team_right_score"`
	UpdatedAt           string  `json:"updated_at"`
}

// LoginRequestSchema defines model for LoginRequestSchema.
type LoginRequestSchema struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponseSchema defines model for LoginResponseSchema.
type LoginResponseSchema struct {
	RefreshToken string `json:"refresh_token"`
	SessionToken string `json:"session_token"`
}

// RefreshTokenResponseSchema defines model for RefreshTokenResponseSchema.
type RefreshTokenResponseSchema struct {
	SessionToken string `json:"session_token"`
}

// SignupRequestSchema defines model for SignupRequestSchema.
type SignupRequestSchema struct {
	Email          openapi_types.Email `json:"email"`
	Password       string              `json:"password"`
	PasswordRepeat string              `json:"password_repeat"`
}

// ErrorResponseSchema defines model for ErrorResponseSchema.
type ErrorResponseSchema = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequestSchema

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequestSchema
