/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameStep } from './GameStep';
import {
    GameStepFromJSON,
    GameStepFromJSONTyped,
    GameStepToJSON,
} from './GameStep';

/**
 * 
 * @export
 * @interface AddGameStepsRequestSchema
 */
export interface AddGameStepsRequestSchema {
    /**
     * 
     * @type {Array<GameStep>}
     * @memberof AddGameStepsRequestSchema
     */
    steps: Array<GameStep>;
}

/**
 * Check if a given object implements the AddGameStepsRequestSchema interface.
 */
export function instanceOfAddGameStepsRequestSchema(value: object): value is AddGameStepsRequestSchema {
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function AddGameStepsRequestSchemaFromJSON(json: any): AddGameStepsRequestSchema {
    return AddGameStepsRequestSchemaFromJSONTyped(json, false);
}

export function AddGameStepsRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddGameStepsRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': ((json['steps'] as Array<any>).map(GameStepFromJSON)),
    };
}

export function AddGameStepsRequestSchemaToJSON(value?: AddGameStepsRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'steps': ((value['steps'] as Array<any>).map(GameStepToJSON)),
    };
}

