/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddPlayerRequestSchema
 */
export interface AddPlayerRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof AddPlayerRequestSchema
     */
    name: string;
}

/**
 * Check if a given object implements the AddPlayerRequestSchema interface.
 */
export function instanceOfAddPlayerRequestSchema(value: object): value is AddPlayerRequestSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AddPlayerRequestSchemaFromJSON(json: any): AddPlayerRequestSchema {
    return AddPlayerRequestSchemaFromJSONTyped(json, false);
}

export function AddPlayerRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPlayerRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AddPlayerRequestSchemaToJSON(value?: AddPlayerRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

