/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGameHistoryRequestSchema
 */
export interface CreateGameHistoryRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof CreateGameHistoryRequestSchema
     */
    playerPosition: CreateGameHistoryRequestSchemaPlayerPositionEnum;
}


/**
 * @export
 */
export const CreateGameHistoryRequestSchemaPlayerPositionEnum = {
    LeftOddPlayer: 'left_odd_player',
    LeftEvenPlayer: 'left_even_player',
    RightOddPlayer: 'right_odd_player',
    RightEvenPlayer: 'right_even_player'
} as const;
export type CreateGameHistoryRequestSchemaPlayerPositionEnum = typeof CreateGameHistoryRequestSchemaPlayerPositionEnum[keyof typeof CreateGameHistoryRequestSchemaPlayerPositionEnum];


/**
 * Check if a given object implements the CreateGameHistoryRequestSchema interface.
 */
export function instanceOfCreateGameHistoryRequestSchema(value: object): value is CreateGameHistoryRequestSchema {
    if (!('playerPosition' in value) || value['playerPosition'] === undefined) return false;
    return true;
}

export function CreateGameHistoryRequestSchemaFromJSON(json: any): CreateGameHistoryRequestSchema {
    return CreateGameHistoryRequestSchemaFromJSONTyped(json, false);
}

export function CreateGameHistoryRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameHistoryRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'playerPosition': json['player_position'],
    };
}

export function CreateGameHistoryRequestSchemaToJSON(value?: CreateGameHistoryRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'player_position': value['playerPosition'],
    };
}

