/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGamePlayerRequestSchema
 */
export interface CreateGamePlayerRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof CreateGamePlayerRequestSchema
     */
    playerPosition: CreateGamePlayerRequestSchemaPlayerPositionEnum;
}


/**
 * @export
 */
export const CreateGamePlayerRequestSchemaPlayerPositionEnum = {
    LeftOddPlayer: 'left_odd_player',
    LeftEvenPlayer: 'left_even_player',
    RightOddPlayer: 'right_odd_player',
    RightEvenPlayer: 'right_even_player'
} as const;
export type CreateGamePlayerRequestSchemaPlayerPositionEnum = typeof CreateGamePlayerRequestSchemaPlayerPositionEnum[keyof typeof CreateGamePlayerRequestSchemaPlayerPositionEnum];


/**
 * Check if a given object implements the CreateGamePlayerRequestSchema interface.
 */
export function instanceOfCreateGamePlayerRequestSchema(value: object): value is CreateGamePlayerRequestSchema {
    if (!('playerPosition' in value) || value['playerPosition'] === undefined) return false;
    return true;
}

export function CreateGamePlayerRequestSchemaFromJSON(json: any): CreateGamePlayerRequestSchema {
    return CreateGamePlayerRequestSchemaFromJSONTyped(json, false);
}

export function CreateGamePlayerRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGamePlayerRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'playerPosition': json['player_position'],
    };
}

export function CreateGamePlayerRequestSchemaToJSON(value?: CreateGamePlayerRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'player_position': value['playerPosition'],
    };
}

