/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameHistory } from './GameHistory';
import {
    GameHistoryFromJSON,
    GameHistoryFromJSONTyped,
    GameHistoryToJSON,
} from './GameHistory';

/**
 * 
 * @export
 * @interface GetGamePlayer200Response
 */
export interface GetGamePlayer200Response {
    /**
     * 
     * @type {GameHistory}
     * @memberof GetGamePlayer200Response
     */
    gameHistory: GameHistory;
}

/**
 * Check if a given object implements the GetGamePlayer200Response interface.
 */
export function instanceOfGetGamePlayer200Response(value: object): value is GetGamePlayer200Response {
    if (!('gameHistory' in value) || value['gameHistory'] === undefined) return false;
    return true;
}

export function GetGamePlayer200ResponseFromJSON(json: any): GetGamePlayer200Response {
    return GetGamePlayer200ResponseFromJSONTyped(json, false);
}

export function GetGamePlayer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGamePlayer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'gameHistory': GameHistoryFromJSON(json['game_history']),
    };
}

export function GetGamePlayer200ResponseToJSON(value?: GetGamePlayer200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'game_history': GameHistoryToJSON(value['gameHistory']),
    };
}

