/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface GetLoggedInUser200Response
 */
export interface GetLoggedInUser200Response {
    /**
     * 
     * @type {User}
     * @memberof GetLoggedInUser200Response
     */
    user: User;
}

/**
 * Check if a given object implements the GetLoggedInUser200Response interface.
 */
export function instanceOfGetLoggedInUser200Response(value: object): value is GetLoggedInUser200Response {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function GetLoggedInUser200ResponseFromJSON(json: any): GetLoggedInUser200Response {
    return GetLoggedInUser200ResponseFromJSONTyped(json, false);
}

export function GetLoggedInUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLoggedInUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
    };
}

export function GetLoggedInUser200ResponseToJSON(value?: GetLoggedInUser200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': UserToJSON(value['user']),
    };
}

