/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPlayers200ResponsePagination
 */
export interface ListPlayers200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof ListPlayers200ResponsePagination
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof ListPlayers200ResponsePagination
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof ListPlayers200ResponsePagination
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof ListPlayers200ResponsePagination
     */
    pageSize: number;
}

/**
 * Check if a given object implements the ListPlayers200ResponsePagination interface.
 */
export function instanceOfListPlayers200ResponsePagination(value: object): value is ListPlayers200ResponsePagination {
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function ListPlayers200ResponsePaginationFromJSON(json: any): ListPlayers200ResponsePagination {
    return ListPlayers200ResponsePaginationFromJSONTyped(json, false);
}

export function ListPlayers200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPlayers200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'totalItems': json['totalItems'],
        'totalPages': json['totalPages'],
        'currentPage': json['currentPage'],
        'pageSize': json['pageSize'],
    };
}

export function ListPlayers200ResponsePaginationToJSON(value?: ListPlayers200ResponsePagination | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
        'pageSize': value['pageSize'],
    };
}

