/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Game } from './Game';
import {
    GameFromJSON,
    GameFromJSONTyped,
    GameToJSON,
} from './Game';

/**
 * 
 * @export
 * @interface ListActiveGames200Response
 */
export interface ListActiveGames200Response {
    /**
     * 
     * @type {Array<Game>}
     * @memberof ListActiveGames200Response
     */
    games?: Array<Game>;
}

/**
 * Check if a given object implements the ListActiveGames200Response interface.
 */
export function instanceOfListActiveGames200Response(value: object): value is ListActiveGames200Response {
    return true;
}

export function ListActiveGames200ResponseFromJSON(json: any): ListActiveGames200Response {
    return ListActiveGames200ResponseFromJSONTyped(json, false);
}

export function ListActiveGames200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListActiveGames200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'games': json['games'] == null ? undefined : ((json['games'] as Array<any>).map(GameFromJSON)),
    };
}

export function ListActiveGames200ResponseToJSON(value?: ListActiveGames200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'games': value['games'] == null ? undefined : ((value['games'] as Array<any>).map(GameToJSON)),
    };
}

