/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePlayerWithIdRequest
 */
export interface UpdatePlayerWithIdRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePlayerWithIdRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdatePlayerWithIdRequest interface.
 */
export function instanceOfUpdatePlayerWithIdRequest(value: object): value is UpdatePlayerWithIdRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdatePlayerWithIdRequestFromJSON(json: any): UpdatePlayerWithIdRequest {
    return UpdatePlayerWithIdRequestFromJSONTyped(json, false);
}

export function UpdatePlayerWithIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePlayerWithIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdatePlayerWithIdRequestToJSON(value?: UpdatePlayerWithIdRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

