/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetGameStatistics200Response,
} from '../models/index';
import {
    GetGameStatistics200ResponseFromJSON,
    GetGameStatistics200ResponseToJSON,
} from '../models/index';

export interface GetGameStatisticsRequest {
    gameId: string;
}

/**
 * 
 */
export class GameApi extends runtime.BaseAPI {

    /**
     * End games which are abandoned after a time
     */
    async endAbandonedGamesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-abandoned-games`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * End games which are abandoned after a time
     */
    async endAbandonedGames(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.endAbandonedGamesRaw(initOverrides);
    }

    /**
     * Generate statistics for players that has latest game in timespan
     */
    async generateRecentStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/generate-recent-statistics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Generate statistics for players that has latest game in timespan
     */
    async generateRecentStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.generateRecentStatisticsRaw(initOverrides);
    }

    /**
     * Get game statistics
     */
    async getGameStatisticsRaw(requestParameters: GetGameStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetGameStatistics200Response>> {
        if (requestParameters['gameId'] == null) {
            throw new runtime.RequiredError(
                'gameId',
                'Required parameter "gameId" was null or undefined when calling getGameStatistics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/game/{game_id}/statistics`.replace(`{${"game_id"}}`, encodeURIComponent(String(requestParameters['gameId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGameStatistics200ResponseFromJSON(jsonValue));
    }

    /**
     * Get game statistics
     */
    async getGameStatistics(requestParameters: GetGameStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetGameStatistics200Response> {
        const response = await this.getGameStatisticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
