/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SignupRequestSchema,
} from '../models/index';
import {
    SignupRequestSchemaFromJSON,
    SignupRequestSchemaToJSON,
} from '../models/index';

export interface SignupClubOwnerRequest {
    signupRequestSchema: SignupRequestSchema;
}

export interface SignupPlayerRequest {
    signupRequestSchema: SignupRequestSchema;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     */
    async signupClubOwnerRaw(requestParameters: SignupClubOwnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signupRequestSchema'] == null) {
            throw new runtime.RequiredError(
                'signupRequestSchema',
                'Required parameter "signupRequestSchema" was null or undefined when calling signupClubOwner().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/signup-club-owner`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestSchemaToJSON(requestParameters['signupRequestSchema']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signupClubOwner(requestParameters: SignupClubOwnerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signupClubOwnerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async signupPlayerRaw(requestParameters: SignupPlayerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['signupRequestSchema'] == null) {
            throw new runtime.RequiredError(
                'signupRequestSchema',
                'Required parameter "signupRequestSchema" was null or undefined when calling signupPlayer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/signup-player`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupRequestSchemaToJSON(requestParameters['signupRequestSchema']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signupPlayer(requestParameters: SignupPlayerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.signupPlayerRaw(requestParameters, initOverrides);
    }

}
