/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameStatistic
 */
export interface GameStatistic {
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    totalGameTime: string;
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    leftConsecutivePoints: string;
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    rightConsecutivePoints: string;
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    longestPoint: string;
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    shortestPoint: string;
    /**
     * 
     * @type {string}
     * @memberof GameStatistic
     */
    averagePerPoint: string;
}

/**
 * Check if a given object implements the GameStatistic interface.
 */
export function instanceOfGameStatistic(value: object): value is GameStatistic {
    if (!('totalGameTime' in value) || value['totalGameTime'] === undefined) return false;
    if (!('leftConsecutivePoints' in value) || value['leftConsecutivePoints'] === undefined) return false;
    if (!('rightConsecutivePoints' in value) || value['rightConsecutivePoints'] === undefined) return false;
    if (!('longestPoint' in value) || value['longestPoint'] === undefined) return false;
    if (!('shortestPoint' in value) || value['shortestPoint'] === undefined) return false;
    if (!('averagePerPoint' in value) || value['averagePerPoint'] === undefined) return false;
    return true;
}

export function GameStatisticFromJSON(json: any): GameStatistic {
    return GameStatisticFromJSONTyped(json, false);
}

export function GameStatisticFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatistic {
    if (json == null) {
        return json;
    }
    return {
        
        'totalGameTime': json['total_game_time'],
        'leftConsecutivePoints': json['left_consecutive_points'],
        'rightConsecutivePoints': json['right_consecutive_points'],
        'longestPoint': json['longest_point'],
        'shortestPoint': json['shortest_point'],
        'averagePerPoint': json['average_per_point'],
    };
}

export function GameStatisticToJSON(value?: GameStatistic | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total_game_time': value['totalGameTime'],
        'left_consecutive_points': value['leftConsecutivePoints'],
        'right_consecutive_points': value['rightConsecutivePoints'],
        'longest_point': value['longestPoint'],
        'shortest_point': value['shortestPoint'],
        'average_per_point': value['averagePerPoint'],
    };
}

