/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramMedia
 */
export interface InstagramMedia {
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    mediaId: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    mediaType: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    mediaUrl: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    permalink: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    postedAt: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramMedia
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the InstagramMedia interface.
 */
export function instanceOfInstagramMedia(value: object): value is InstagramMedia {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mediaId' in value) || value['mediaId'] === undefined) return false;
    if (!('mediaType' in value) || value['mediaType'] === undefined) return false;
    if (!('mediaUrl' in value) || value['mediaUrl'] === undefined) return false;
    if (!('permalink' in value) || value['permalink'] === undefined) return false;
    if (!('postedAt' in value) || value['postedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function InstagramMediaFromJSON(json: any): InstagramMedia {
    return InstagramMediaFromJSONTyped(json, false);
}

export function InstagramMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'mediaId': json['media_id'],
        'mediaType': json['media_type'],
        'mediaUrl': json['media_url'],
        'permalink': json['permalink'],
        'postedAt': json['posted_at'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function InstagramMediaToJSON(value?: InstagramMedia | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'media_id': value['mediaId'],
        'media_type': value['mediaType'],
        'media_url': value['mediaUrl'],
        'permalink': value['permalink'],
        'posted_at': value['postedAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

