/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponseSchema
 */
export interface LoginResponseSchema {
    /**
     * 
     * @type {string}
     * @memberof LoginResponseSchema
     */
    sessionToken: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseSchema
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the LoginResponseSchema interface.
 */
export function instanceOfLoginResponseSchema(value: object): value is LoginResponseSchema {
    if (!('sessionToken' in value) || value['sessionToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function LoginResponseSchemaFromJSON(json: any): LoginResponseSchema {
    return LoginResponseSchemaFromJSONTyped(json, false);
}

export function LoginResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionToken': json['session_token'],
        'refreshToken': json['refresh_token'],
    };
}

export function LoginResponseSchemaToJSON(value?: LoginResponseSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_token': value['sessionToken'],
        'refresh_token': value['refreshToken'],
    };
}

