/* tslint:disable */
/* eslint-disable */
/**
 * tzetypes-badminton
 * tzetypes-badminton
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequestSchema
 */
export interface SignupRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequestSchema
     */
    passwordRepeat: string;
}

/**
 * Check if a given object implements the SignupRequestSchema interface.
 */
export function instanceOfSignupRequestSchema(value: object): value is SignupRequestSchema {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passwordRepeat' in value) || value['passwordRepeat'] === undefined) return false;
    return true;
}

export function SignupRequestSchemaFromJSON(json: any): SignupRequestSchema {
    return SignupRequestSchemaFromJSONTyped(json, false);
}

export function SignupRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'passwordRepeat': json['password_repeat'],
    };
}

export function SignupRequestSchemaToJSON(value?: SignupRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'password_repeat': value['passwordRepeat'],
    };
}

