// Package oapiprivate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package oapiprivate

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AddPlayerRequestSchema defines model for AddPlayerRequestSchema.
type AddPlayerRequestSchema struct {
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	CreatedAt string `json:"created_at"`
	Email     string `json:"email"`
	Id        string `json:"id"`
	UpdatedAt string `json:"updated_at"`
}

// CurrentUserResponseSchema defines model for CurrentUserResponseSchema.
type CurrentUserResponseSchema struct {
	User User `json:"user"`
}

// ErrorResponseSchema defines model for ErrorResponseSchema.
type ErrorResponseSchema = Error

// AddPlayerJSONRequestBody defines body for AddPlayer for application/json ContentType.
type AddPlayerJSONRequestBody = AddPlayerRequestSchema
