openapi: "3.0.0"
info:
  version: 1.0.0
  title: tzetypes-badminton
  description: tzetypes-badminton
  contact:
    name: ezekiel
    url: https://github.com/ezekielchow
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - BearerAuth: []
paths:
  /dashboard:
    get:
      operationId: dashboard
      responses:
        "204":
          description: dashboard success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

  /logout:
    get:
      operationId: logout
      tags:
        - users
      responses:
        "204":
          description: logout success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

  /player/add:
    post:
      operationId: add player
      tags:
        - players
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPlayerRequestSchema"
      responses:
        "201":
          description: add player success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

components:
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    AddPlayerRequestSchema:
      type: object
      required:
        - name
      properties:
        name:
          type: string

  responses:
    ErrorResponseSchema:
      description: Error res
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
