openapi: "3.0.0"
info:
  version: 1.0.0
  title: tzetypes-badminton
  description: tzetypes-badminton
  contact:
    name: ezekiel
    url: https://github.com/ezekielchow
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - BearerAuth: []
paths:
  /dashboard:
    get:
      operationId: dashboard
      responses:
        "204":
          description: dashboard success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

  /logout:
    get:
      operationId: logout
      tags:
        - users
      responses:
        "204":
          description: logout success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

  /players/add:
    post:
      operationId: add player
      tags:
        - players
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPlayerRequestSchema"
      responses:
        "201":
          description: add player success
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

  /users/current:
    get:
      operationId: get logged in user # Corrected Typo
      tags:
        - users
      responses:
        "200":
          description: get user success
          $ref: "#/components/responses/CurrentUserResponseSchema"
        default:
          $ref: "#/components/responses/ErrorResponseSchema"

components:
  securitySchemes: # Added missing security scheme
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    AddPlayerRequestSchema:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    User:
      type: object
      required:
        - id
        - email
        - created_at
        - updated_at
      properties:
        id:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string

  responses:
    ErrorResponseSchema:
      description: Error res
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    CurrentUserResponseSchema:
      description: current user success
      content:
        application/json:
          schema:
            type: object
            required:
              - user
            properties:
              user:
                $ref: "#/components/schemas/User"
